# Generated by Django 6.0.4 on 2026-04-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_artigo_imagem_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='artigos.categoria'),
        ),
    ]
