# Generated by Django 6.0.4 on 2026-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_categoria_categoria_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='artigos/documentos/'),
        ),
    ]
