# Generated by Django 6.0.4 on 2026-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0006_artigo_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
