# Generated by Django 6.0.4 on 2026-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0007_alter_artigo_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='autor_nome',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='nome_autor_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
