# Generated by Django 6.0.4 on 2026-04-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0008_artigo_autor_nome_artigo_nome_autor_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='autor_nome',
        ),
        migrations.AlterField(
            model_name='artigo',
            name='nome_autor_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome autor snapshot'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artigos', to='artigos.tag'),
        ),
    ]
