# Generated by Django 6.0.4 on 2026-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0010_alter_tag_options_artigo_grupos_permitidos_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='grupos_permitidos',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
